name: EMM Radar (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R deps for EMM Radar
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-public-rspm: true
          extra-packages: |
            any::jsonlite
            any::httr2
            any::xml2
            any::rvest
            any::dplyr
            any::stringr
            any::purrr
            any::tibble

      - name: Run Radar (Rscript)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          # Modifica questa lista se vuoi altre pagine EMM
          EMM_URLS: "https://emm.newsbrief.eu/NewsBrief/countryedition/it/TN.html,https://emm.newsbrief.eu/NewsBrief/countryedition/it/IT.html"
          EMM_OUTPUT: data/sources/emm_radar.json
          EMM_MAX_ITEMS: "40"
        run: Rscript scripts/emm_radar.R

      - name: Commit radar data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(radar): refresh EMM Radar data"
