name: Daily RSS Digest

on:
  schedule:
    - cron: "0 5 * * *"   # 07:00 Roma (UTC+2 estate)
    - cron: "0 10 * * *"  # 12:00 Roma
    - cron: "0 15 * * *"  # 17:00 Roma
    - cron: "0 19 * * *"  # 21:00 Roma
    - cron: "0 22 * * *"  # 00:00 Roma
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 lxml python-dateutil

      - name: Run digest script
        run: |
          python make_digest.py

      - name: Add timestamp to digest
        run: |
          now=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo -e "# Digest aggiornato: $now\n\n$(cat digest.md)" > digest.md

          - name: Install deps
  run: pip install -r requirements.txt


     - name: Commit & push changes
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git add digest.md data/sources/*.csv || true
    git commit -m "Update digest + sources CSV" || echo "Nothing to commit"
    git push

