name: Daily RSS Digest

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"  # 06:30 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build digest
        run: python make_digest.py

      - name: Commit digest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add digest.md
          git commit -m "Update digest.md [skip ci]" || echo "No changes to commit"
          git push

