name: Daily RSS Digest

on:
  schedule:
    - cron: "30 6 * * *"   # 06:30 UTC ogni giorno
  workflow_dispatch:        # abilita il pulsante "Run workflow"

permissions:
  contents: write           # serve per committare digest.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate digest.md
        run: |
          python make_digest.py --feeds feeds.txt --max-per-feed 10 --out digest.md
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add digest.md
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "chore: update daily digest [skip ci]"
          git push
