name: Digest (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R deps for EMM Radar
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-public-rspm: true
          extra-packages: |
            any::jsonlite
            any::httr2
            any::xml2
            any::rvest
            any::dplyr
            any::stringr
            any::purrr
            any::tibble

      - name: Run EMM Radar (Rscript)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          EMM_URLS: "https://emm.newsbrief.eu/NewsBrief/countryedition/it/TN.html,https://emm.newsbrief.eu/NewsBrief/countryedition/it/IT.html"
          EMM_OUTPUT: data/sources/emm_radar.json
          EMM_MAX_ITEMS: "40"
        run: Rscript scripts/emm_radar.R

      - name: Build digest (Python)
        run: python make_digest.py

      - name: Commit & push digest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(digest): update digest.md (with EMM Radar)"
